// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-token-balance.ts
import { createClient } from "npm:@supabase/supabase-js@^2.104.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_token_balance_default = defineTool({
  name: "get_token_balance",
  title: "Get token balance",
  description: "Returns the signed-in user's current vocal token balance.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("profiles").select("token_balance").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const balance = data?.token_balance ?? 0;
    return {
      content: [{ type: "text", text: `Balance: ${balance} tokens` }],
      structuredContent: { balance }
    };
  }
});

// src/lib/mcp/tools/list-recent-transactions.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.104.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_recent_transactions_default = defineTool2({
  name: "list_recent_transactions",
  title: "List recent token transactions",
  description: "Lists the signed-in user's most recent token transactions (purchases and spends).",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(10).describe("How many transactions to return (1-50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("token_transactions").select("id, tokens_credited, price_id, reason, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(Math.min(50, Math.max(1, limit ?? 10)));
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { transactions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-channels.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.104.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_channels_default = defineTool3({
  name: "list_my_channels",
  title: "List my live channels",
  description: "Lists live channels owned by the signed-in user, including visibility and per-minute rate.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser3(ctx).from("live_channels").select("id, name, description, visibility, min_tokens, active_boxes, multi_window, created_at").eq("owner_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(50);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { channels: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "hvvxklhasdnwyzqloeah";
var mcp_default = defineMcp({
  name: "queentoken-mcp",
  title: "QueenToken MCP",
  version: "0.1.0",
  instructions: "Tools for the QueenToken vocal-token app. Use `get_token_balance` to read the signed-in user's balance, `list_recent_transactions` to review their purchase/spend history, and `list_my_channels` to inspect live channels they own.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_token_balance_default, list_recent_transactions_default, list_my_channels_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
